### PR TITLE
issue #101 resolved

### PR DESCRIPTION
**Pull request by shubhamkakkar**
Will soon upload a working example under my github handle

PS: Sorry for the wrong commit message

### CODE REVIEW

**Comment by palingheorghe** [comment]
Hi @shubhamkakkar ! Thanks for the PR and for using Hooks. I have a question regarding those files in the `.idea` directory. I'm not sure what's up with them what are they used for and why are those there? I think those files should be ignored for the PR. 

Alin

**Comment by shubhamkakkar** [comment]
It's strange, those shouldn't be uploaded !! i will amend this by tonight.

**Comment by shubhamkakkar** [comment]
I have removed the 
```
.idea
```
 folder @palingheorghe

**Comment by palingheorghe** [comment]
Closed as mentioned in #116 .

**Pull request closed without merging**
