### PR TITLE
Created: Switch component.

### PR DESCRIPTION
**Pull request by antelbra**
### Created: Switch Component
I've done the Switch Component, but I'd like you to review and tell if there is something that can be done better.

✌️

### CODE REVIEW

**Comment by palingheorghe** [comment]
Related to #62.

**Comment by antelbra** [comment]
Great! I’ll take your indications and improve the component ✌️

**Comment by palingheorghe** [comment]
Hi @antelbra, 

I was wondering if you still work on this component? If you could finish implementing this component that would help us a lot! ❤️

Thanks!

**Comment by antelbra** [comment]
Hi @palingheorghe, I had some personal issues but I think I could finish the component and make the PR this weekend 😃

**Pull request merged**
