### PR TITLE
Components/toast-notification

### PR DESCRIPTION
**Pull request by extenss**
related to #86

### CODE REVIEW

**Comment by VictorAtPL** [comment]
Hi,

How to use this?

I've added such code into my component:
```
                <Toast isShow={errorShow} position={"bottom"}>
                    Cośtam jakośtam.
                </Toast>
```
After I set `errorShow` on other button click to `true`, app crashes (no log showed in React Native Debugger).

**Comment by palingheorghe** [comment]
Hi @VictorAtPL , I've seen you've pushed a commit to your fork of Galio. Have you managed to solve this issue? 
@extenss could you help us with using this component? 

Thanks everybody ❤️

**Comment by VictorAtPL** [comment]
@palingheorghe
Yes, I am using the modified version of this Pull Request in my app, which is in alpha stage right now, although I haven't tested it inside out.

I can prepare a patch tomorrow.

**Comment by palingheorghe** [comment]
That'd be great @VictorAtPL ! I'm trying to push forward the development of this version, we need to get to v0.6 and help more people ❤️

Alin

**Comment by VictorAtPL** [comment]
@palingheorghe 
Ok, I've pulled @extenss Pull Request and applied my fixes. You can see changes here: https://github.com/VictorAtPL/galio/commit/ea42b000b110edeb23cbc7452a9f83984bd0bca2

I could open new pull request, but I don't want to stole @extenss code. :)

Basically the `position` attribute must be changed and `styles` attribute must be added (styling was not working without it).

**Comment by palingheorghe** [comment]
@VictorAtPL 
I don't think you're stealing anybody's code, I'm pretty sure he's getting credited for whatever he has written. Could you please open up a PR with your new code?

**Comment by VictorAtPL** [comment]
@palingheorghe I opened #112.

**Pull request closed without merging**
